version: "3"
services:
  rainloop:
    image: xgaia/rainloop:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ${DATA_ROOT_DIR:-/tmp}/rainloop/data:/var/www/html/data
